### ISSUE TITLE
Odd error causing crash when removing users

### ISSUE THREAD

**Issue by ImCarsen** [ImCarsen/The-Wandering-Cosmos#1]
```
Traceback (most recent call last):
  File "D:\Code Workspace\The Wandering Cosmos\main.py", line 439, in <module>
    asyncio.run(MainLoop())
  File "C:\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "D:\Code Workspace\The Wandering Cosmos\main.py", line 403, in MainLoop
    await greatErasure(redditConnect())
  File "D:\Code Workspace\The Wandering Cosmos\main.py", line 344, in greatErasure
    await removeUser(redditConnect(), x)
  File "D:\Code Workspace\The Wandering Cosmos\main.py", line 176, in removeUser
    await subAwait.contributor.remove(user)
  File "C:\Python310\lib\site-packages\asyncpraw\models\reddit\subreddit.py", line 3243, in remove
    await self.subreddit._reddit.post(url, data=data)
  File "C:\Python310\lib\site-packages\asyncpraw\util\deprecate_args.py", line 51, in wrapped
    return await _wrapper(*args, **kwargs)
  File "C:\Python310\lib\site-packages\asyncpraw\reddit.py", line 920, in post
    return await self._objectify_request(
  File "C:\Python310\lib\site-packages\asyncpraw\reddit.py", line 815, in _objectify_request
    await self.request(
  File "C:\Python310\lib\site-packages\asyncpraw\util\deprecate_args.py", line 51, in wrapped
    return await _wrapper(*args, **kwargs)
  File "C:\Python310\lib\site-packages\asyncpraw\reddit.py", line 1032, in request
    return await self._core.request(
  File "C:\Python310\lib\site-packages\asyncprawcore\sessions.py", line 370, in request
    return await self._request_with_retries(
  File "C:\Python310\lib\site-packages\asyncprawcore\sessions.py", line 307, in _request_with_retries
    raise self.STATUS_EXCEPTIONS[response.status](response)
asyncprawcore.exceptions.BadRequest: received 400 HTTP response
Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x0000019FC74FFDC0>
transport: <_ProactorSocketTransport fd=756 read=<_OverlappedFuture cancelled>>
Traceback (most recent call last):
  File "C:\Python310\lib\asyncio\sslproto.py", line 690, in _process_write_backlog
    self._transport.write(chunk)
  File "C:\Python310\lib\asyncio\proactor_events.py", line 361, in write
    self._loop_writing(data=bytes(data))
  File "C:\Python310\lib\asyncio\proactor_events.py", line 397, in _loop_writing
    self._write_fut = self._loop._proactor.send(self._sock, data)
AttributeError: 'NoneType' object has no attribute 'send'
Exception ignored in: <function _SSLProtocolTransport.__del__ at 0x0000019FC6281240>
Traceback (most recent call last):
  File "C:\Python310\lib\asyncio\sslproto.py", line 321, in __del__
  File "C:\Python310\lib\asyncio\sslproto.py", line 316, in close
  File "C:\Python310\lib\asyncio\sslproto.py", line 599, in _start_shutdown
  File "C:\Python310\lib\asyncio\sslproto.py", line 604, in _write_appdata
  File "C:\Python310\lib\asyncio\sslproto.py", line 712, in _process_write_backlog
  File "C:\Python310\lib\asyncio\sslproto.py", line 726, in _fatal_error
  File "C:\Python310\lib\asyncio\proactor_events.py", line 151, in _force_close
  File "C:\Python310\lib\asyncio\base_events.py", line 750, in call_soon
  File "C:\Python310\lib\asyncio\base_events.py", line 515, in _check_closed
RuntimeError: Event loop is closed
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000019FC73F8460>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000019FC74FC520>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x0000019FC74BA9E0>, 1071237.328)]']
connector: <aiohttp.connector.TCPConnector object at 0x0000019FC74FEA10>
```

Seems to be deleted users causing the crash when the bot tries to remove them

**Comment by ImCarsen** [comment]
May have the fix, just put `await subAwait.contributor.remove(user)` into a try-except for exception handling

**Comment by ImCarsen** [comment]
Fixed (kinda maybe) by adding a try-except to handle the exceptions in the [removeUser function](https://github.com/ImCarsen/The-Wandering-Cosmos/blob/master/main.py#L163) at [line 175](https://github.com/ImCarsen/The-Wandering-Cosmos/blob/master/main.py#L175)
